#语法格式 key: 空格(N+)val 。兄弟关系保持在同级。父子关系，需要换行缩进
#2、大小写敏感
#server:
#  port: 8083
#  compression:
#    enabled: false

#########################################
#与实体对象匹配
#########################################
# 1、字符串 可以直接编写（中文与字符） "" : 里面的内容不会被转义 \r \n  保持原有含义 。   '' ： 会被转义 \n 原封不动的输出
# 2、map与list或set集合支持行内写法 {key: val , key1: val1}
person:
  name: '张三\n李四'
  age: 22
  birthday: 2021/08/31
  last-name: wu
  list:
    - cat
    - dog
  email: checy@163.com
  map: {k1: lily , k2: lucy}
  car:
    name: 兰博基尼
    color: 红色

wx:
  api: https://wx.open.xxx/pay


##########
#配置日志相关
logging:
  level: debug
##################
#数据源配置
##################
spring:
  datasource:
    url: jdbc:mysql://192.168.8.140:3306/fellows7_springboot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sifu_2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
################################
#配置Redis连接的主机
################################
  redis:
    host: 192.168.8.140
################################
#配置RabbitMQ连接的主机
################################
  rabbitmq:
    host: 192.168.8.140

######################
#yml中对Mybatis配置支持
######################
mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰命名自动识别配置



#文档块,多文档块、被多属性文件所取缔。不推荐使用了
---
server:
  port: 8087
spring:
  profiles: dev
---
server:
  port: 8088
spring:
  profiles: prod
